Add Git workflow readme
CyrdGames/GodotPlatformer pull request #2
Opened 2020-05-22 02:33 UTC by victorlyan

close #1

2020-05-22 04:58 UTC, OriginalMichael requested changes

2020-05-22 04:58 UTC, OriginalMichael commented on readmes/readme_git_workflow.md
> +All issues/tickets should be associated with the StudyClicker project to be placed on the board, containing four main phases of development: To do, In progress, In review, and Done.
Rename project

2020-05-24 21:16 UTC, arcyleung approved these changes

2020-05-25 03:07 UTC, OriginalMichael approved these changes

2020-05-26 01:10 UTC, merged